#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
#Load modules
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Summerise taxa summary
compare_categories.py --method adonis -i weighted_unifrac_dm.txt -m mapping_file.tsv -c "SamplePh" -o adonis_ph -n 999
compare_categories.py --method adonis -i weighted_unifrac_dm.txt -m mapping_file.tsv -c "SamplePotassium" -o adonis_K -n 999
compare_categories.py --method adonis -i weighted_unifrac_dm.txt -m mapping_file.tsv -c "SampleMoisture" -o adonis_Mois -n 999
compare_categories.py --method adonis -i weighted_unifrac_dm.txt -m mapping_file.tsv -c "SampleNitrogen" -o adonis_N -n 999
compare_categories.py --method adonis -i weighted_unifrac_dm.txt -m mapping_file.tsv -c "SamplePhosphorus" -o adonis_P -n 999
compare_categories.py --method adonis -i weighted_unifrac_dm.txt -m mapping_file.tsv -c "SampleDepth" -o adonis_depth -n 999
# deactivating environment
source deactivate
